import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./ui/components/header";
import Footer from "./ui/components/footer";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "CV Builder",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<link rel="shortcut icon" href="/favicon-dark-cv-icon.svg" />
				<link
					rel="shortcut icon"
					href="/favicon-light-cv-icon.svg"
					media="(prefers-color-scheme: dark)"
				/>
			</head>
			{/* <Favicon /> */}
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col justify-between min-h-screen`}
			>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
